### ISSUE TITLE
Cant connect to youtube chat

### ISSUE THREAD

**Issue by pawtetius** [onoderis/failchat#14]
2019-09-15 23:39:42,501 INFO [ViewersCounterThread] failchat.viewers.ViewersCounter (ViewersCounter.kt:94) Couldn't update viewers count, channel UCioMh2d_of1G6_yaNVSNshg#YOUTUBE is offline
2019-09-15 23:39:57,911 WARN [YoutubeExecutor] failchat.youtube.YtChatClient (YtChatClient.kt:148) Failed to find stream. Retry in 15000 ms. channelId/broadcastId: 'UCioMh2d_of1G6_yaNVSNshg'
failchat.youtube.BroadcastNotFoundException: Youtube broadcast not found. resource: 'search', channel id: 'UCioMh2d_of1G6_yaNVSNshg'
	at failchat.youtube.YtChatClient.getLiveChatIdRecursiveTask(YtChatClient.kt:125)
	at failchat.youtube.YtChatClient.access$getLiveChatIdRecursiveTask(YtChatClient.kt:43)
	at failchat.youtube.YtChatClient$getLiveChatIdRecursiveTask$2.invoke(YtChatClient.kt:150)
	at failchat.youtube.YtChatClient$getLiveChatIdRecursiveTask$2.invoke(YtChatClient.kt:43)
	at failchat.util.ConcurrentKt$scheduleWithCatch$1.invoke(Concurrent.kt:26)
	at failchat.util.ConcurrentKt$scheduleWithCatch$1.invoke(Concurrent.kt)
	at failchat.util.ConcurrentKt$sam$java_lang_Runnable$0.run(Concurrent.kt)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by onoderis** [comment]
@pawtetius Have you tried to connect by video id?
When you connect by channel id, failchat tries to find a stream on your channel. And often it appears after a while. This issue described [on the wiki](https://github.com/onoderis/failchat/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B#youtube) (in russian).

**Comment by onoderis** [comment]
@pawtetius A little update on the issue. I have tested connection by the channel id, it can't find the stream at all. So it's a bug.
But you can still connect by video id, it works fine.

**Comment by pawtetius** [comment]
@onoderis ok thanks ill try it

**Comment by onoderis** [comment]
@pawtetius It should be working now
